# Form implementation generated from reading ui file 'C:\Users\nsc\Documents\GitHub\LSAT\core\uis\ResultViewer_ui\resultsViewerWofE.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modelTreeWidget = QtWidgets.QTreeWidget(self.tab)
        self.modelTreeWidget.setObjectName("modelTreeWidget")
        self.horizontalLayout_3.addWidget(self.modelTreeWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tableTab = QtWidgets.QWidget()
        self.tableTab.setObjectName("tableTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tableTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableTabGridLayout = QtWidgets.QGridLayout()
        self.tableTabGridLayout.setObjectName("tableTabGridLayout")
        self.horizontalLayout_2.addLayout(self.tableTabGridLayout)
        self.tabWidget.addTab(self.tableTab, "")
        self.graphicsTab = QtWidgets.QWidget()
        self.graphicsTab.setObjectName("graphicsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.graphicsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsTabGridLayout = QtWidgets.QGridLayout()
        self.graphicsTabGridLayout.setObjectName("graphicsTabGridLayout")
        self.verticalLayout.addLayout(self.graphicsTabGridLayout)
        self.tabWidget.addTab(self.graphicsTab, "")
        self.mainGridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.mainGridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelTreeWidget.headerItem().setText(0, _translate("MainWindow", "Info"))
        self.modelTreeWidget.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Seite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tableTab), _translate("MainWindow", "Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphicsTab), _translate("MainWindow", "Graphics"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
