# Form implementation generated from reading ui file 'C:\Users\nsc\Documents\GitHub\LSAT\core\uis\AttributeTable_ui\attributeTable.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AttributeTable(object):
    def setupUi(self, AttributeTable):
        AttributeTable.setObjectName("AttributeTable")
        AttributeTable.resize(792, 530)
        self.centralwidget = QtWidgets.QWidget(AttributeTable)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.mainGridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.mainGridLayout)
        AttributeTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AttributeTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 22))
        self.menubar.setObjectName("menubar")
        AttributeTable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AttributeTable)
        self.statusbar.setObjectName("statusbar")
        AttributeTable.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(AttributeTable)
        self.toolBar.setObjectName("toolBar")
        AttributeTable.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.retranslateUi(AttributeTable)
        QtCore.QMetaObject.connectSlotsByName(AttributeTable)

    def retranslateUi(self, AttributeTable):
        _translate = QtCore.QCoreApplication.translate
        AttributeTable.setWindowTitle(_translate("AttributeTable", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("AttributeTable", "toolBar"))
